language: csharp
solution: ArbitesEto2/ArbitesEto2.sln
install:
- nuget restore ArbitesEto2/ArbitesEto2.sln
- nuget install xunit.runner.console -Version 2.2.0 -OutputDirectory testrunner
script:
- msbuild /p:Configuration=LinuxRelease ArbitesEto2/ArbitesEto2.sln
- mono testrunner/xunit.runner.console.2.2.0/tools/xunit.console.exe ArbitesEto2/ArbitesEto2.Tests/bin/LinuxRelease/net461/ArbitesEto2.Tests.dll
